import { FREE_SLOT_LIMIT } from "./fivemPaths";

// hardcap, rconlog and sessionmanager were deleted from cfx-server-data on
// 2026-07-20, so ensuring them only prints "Couldn't find resource" at boot.
// chat ships inside the artifact under citizen/system_resources.
export const DEFAULT_RESOURCES = [
	"mapmanager",
	"chat",
	"spawnmanager",
	"basic-gamemode",
];

export const serverConfigTemplate = (gamePort: number, hostname: string) => {
	return [
		"# Only change the IP if you're using a server with multiple network interfaces.",
		"# serverk rewrites both endpoints on every boot from the port it gave your server.",
		`endpoint_add_tcp "0.0.0.0:${gamePort}"`,
		`endpoint_add_udp "0.0.0.0:${gamePort}"`,
		"",
		"# These resources will start by default.",
		...DEFAULT_RESOURCES.map((resource) => `ensure ${resource}`),
		"",
		"# This allows players to use scripthook-based plugins such as the legacy Lambda Menu.",
		"sv_scriptHookAllowed 0",
		"",
		"# Uncomment this and set a password to enable RCON.",
		'#set rcon_password ""',
		"",
		"# A comma-separated list of tags for your server.",
		'sets tags "roleplay, arabic"',
		"",
		"# A valid locale identifier for your server's primary language.",
		'sets locale "ar-SA"',
		"",
		"# Set an optional server info and connecting banner image url.",
		'#sets banner_detail "https://url.to/image.png"',
		'#sets banner_connecting "https://url.to/image.png"',
		"",
		"# Set your server's hostname.",
		`sv_hostname "${hostname}"`,
		"",
		"# Set your server's Project Name",
		`sets sv_projectName "${hostname}"`,
		"",
		"# Set your server's Project Description",
		'sets sv_projectDesc "سيرفر فايف إم على سيرفرك"',
		"",
		"# Set Game Build (https://docs.fivem.net/docs/server-manual/server-commands/#sv_enforcegamebuild-build)",
		"#sv_enforceGameBuild 2802",
		"",
		"# Nested configs!",
		"#exec server_internal.cfg",
		"",
		"# Loading a server icon (96x96 PNG file)",
		"#load_server_icon myLogo.png",
		"",
		"# Remove the `#` from the below line if you want your server to be listed as 'private'.",
		'#sv_master1 ""',
		"",
		"# Add system admins",
		"add_ace group.admin command allow # allow all commands",
		"add_ace group.admin command.quit deny # but don't allow quit",
		"add_principal identifier.fivem:1 group.admin # add the admin to the group",
		"",
		"# enable OneSync (required for server-side state awareness)",
		"set onesync on",
		"",
		"# Server player slot limit (see https://fivem.net/server-hosting for limits)",
		`sv_maxclients ${FREE_SLOT_LIMIT}`,
		"",
		"# Steam Web API key, if you want to use Steam authentication",
		'set steam_webApiKey ""',
		"",
		"# License key for your server (https://portal.cfx.re)",
		"# serverk writes an sv_licenseKey line here from the key you paste in the panel.",
		"",
	].join("\n");
};
